[DatabaseConnection]
Host = ""
Port = 3306
User = ""
Pass = ""
Name = ""
StorePlayersName = "store_players"
StoreItemsName = "store_items"
StoreEquipments = "store_equipments"
StoreLogs = "store_logs"

[Commands]
Credits = [ "credits", "tl" ]
Store = [ "store", "shop", "market" ]
Inventory = [ "inv", "inventory" ]
GiveCredits = [ "givecredits" ]
Gift = [ "gift" ]
ResetPlayer = [ "resetplayer" ]
ResetDatabase = [ "resetdatabase" ]
RefreshPlayersCredits = [ "refreshcredits" ]
HideTrails = [ "hidetrails" ]
PlayerSkinsOff = [ "model0", "modeloff" ]
PlayerSkinsOn = [ "model1", "modelon" ]

[DefaultModels]
Terrorist = [ "characters/models/tm_leet/tm_leet_variantj.vmdl" ]
CounterTerrorist = [ "characters/models/ctm_fbi/ctm_fbi_variantb.vmdl" ]
DefaultModelDisableLeg = false

[Credits."@css/vip"]
AmountActive = 10
AmountInActive = 1
AmountKill = 1

[Credits."default"]
Start = 0
IgnoreWarmup = true
IntervalActiveInActive = 60
AmountActive = 10
AmountInActive = 1
AmountKill = 1

[Menu]
EnableConfirmMenu = true
MenuType = "ScreenMenu"
VipFlag = "@css/root"
MenuPressSoundYes = ""
MenuPressSoundNo = ""
CloseMenuAfterSelect = false

[Settings]
Tag = "{red}[Store]"
MaxHealth = 0
MaxArmor = 0
SellRatio = 0.6
ApplyPlayerskinDelay = 0.6
SellUsePurchaseCredit = false
EnableCs2Fixes = false

[Permissions]
Model0Model1Flag = "@css/root"
GiveCredits = "@css/root"
